name: Deploy
on:
  push:
      branches: ["**"]
jobs:
  my_first_job: 
    runs-on: "ubuntu-latest"
    steps:
      - name: Check out repository
        uses: actions/checkout@v4      
      - name: Setup .NET Environment
        uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: '8.0'
      - name: Restore Nuget dependecy
        run: dotnet restore
      - name: Solution Compilation
        run: dotnet build
      - name: Test Compilation
        run: dotnet test <TestProject1>
